"""empty message

Revision ID: 0386216fa174
Revises: 54fbf794a6a8
Create Date: 2021-08-02 17:27:46.995436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0386216fa174'
down_revision = '54fbf794a6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heartbeat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('dataset_no', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('method_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hearbeat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hearbeat',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('dataset_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('method_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('method_name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('heartbeat')
    # ### end Alembic commands ###
