"""empty message

Revision ID: 2f52cae6c94f
Revises: 095d37192f7d
Create Date: 2021-07-30 16:19:32.351955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f52cae6c94f'
down_revision = '095d37192f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=120), nullable=True))
    op.drop_index('email', table_name='user')
    op.create_unique_constraint(None, 'user', ['password'])
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('email', 'user', ['email'], unique=False)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
