"""empty message

Revision ID: 937a2ce11e29
Revises: a762a88d6742
Create Date: 2021-08-02 17:07:17.301927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937a2ce11e29'
down_revision = 'a762a88d6742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ckp_rbk', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('hearbeat', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('ping__echo', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('redundancy', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('voting', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voting', 'id')
    op.drop_column('redundancy', 'id')
    op.drop_column('ping__echo', 'id')
    op.drop_column('hearbeat', 'id')
    op.drop_column('ckp_rbk', 'id')
    # ### end Alembic commands ###
