"""empty message

Revision ID: a762a88d6742
Revises: e3071d7621ae
Create Date: 2021-08-02 15:41:04.277777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a762a88d6742'
down_revision = 'e3071d7621ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hearbeat',
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('dataset_no', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('method_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.drop_table('hear_beat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hear_beat',
    sa.Column('user_email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('dataset_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('method_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('method_name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_email'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('hearbeat')
    # ### end Alembic commands ###
