"""empty message

Revision ID: e3071d7621ae
Revises: 2f52cae6c94f
Create Date: 2021-08-02 15:39:50.966609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3071d7621ae'
down_revision = '2f52cae6c94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ckp_rbk',
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('dataset_no', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('method_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_table('hear_beat',
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('dataset_no', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('method_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_table('ping__echo',
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('dataset_no', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('method_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_table('redundancy',
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('dataset_no', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('method_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_table('voting',
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('dataset_no', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('method_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.drop_index('password', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=False)
    op.create_index('password', 'user', ['password'], unique=False)
    op.drop_table('voting')
    op.drop_table('redundancy')
    op.drop_table('ping__echo')
    op.drop_table('hear_beat')
    op.drop_table('ckp_rbk')
    # ### end Alembic commands ###
